spring:
  task:
    execution:
      pool:
        core-size: 2
      thread-name-prefix: task-demo
    scheduling:
      pool:
        size:  2
      thread-name-prefix: scheduling-demo
my:
  properties:
    id: bear
    name: test
    enable: true