server:
  port: 9000
spring:
  redis:
    database: 0
    password: XEeNxUmPnw3eH7
    port: 6379
    timeout: 3000
    host: 192.168.99.229
  cache:
    cache-names: IndexController
    type: redis
logging:
  level:
    root: info